### ISSUE TITLE
Installation script

### ISSUE THREAD

**Issue by RaphaelBunck** [RescueOnWheels/Rover#21]
This is supposed to be in RescueOnWheels/Scriptor but who gives a shit at this point.
+ Installs NodeJS
+ Clones all repo's
+ Runs "npm i" in all repo's
+ Tests if everything is installed correctly

**Comment by mvegter** [comment]
Issue moved to [RescueOnWheels/Scriptor #11](https://github.com/RescueOnWheels/Scriptor/issues/11) via [**ZenHub**](https://www.zenhub.com/)
